### ISSUE TITLE
How does `stringsElement` work?

### ISSUE THREAD

**Issue by Eraldo** [thevladeffect/ngx-typed-js#1]
I tried to get `stringsElement` to work, without success.

Can you please provide an example or tell me how to go about using it? :)

Best,
Eraldo

**Comment by thevladeffect** [comment]
Everything works exactly like it would in Typed.js, this library is just a wrapper for it.

```
<ngx-typed-js [stringsElement]="'#test'">
  <h1 class="typing"></h1>
</ngx-typed-js>

<div id="test" style="display: none">
  <span>
    Hello, this is a test.
  </span>
  <span>
    I am a testy test.
  </span>
</div>
```
