### ISSUE TITLE
Does not working on Angular 9

### ISSUE THREAD

**Issue by KristofKreimeyer** [thevladeffect/ngx-typed-js#3]
Hi guys,

i tried to use your typed-js solution in angular 9 and it seems to me that it is not compatible. 
Do you have any solution?

Greetz
Kristof

**Comment by thevladeffect** [comment]
I'll take a look this week.

**Comment by thevladeffect** [comment]
There's no reason this wouldn't have worked for you on Angular 9. It probably only gave you some warning regarding a mismatch in dependencies. Published `v2.0.0` with updated dependencies.
