### ISSUE TITLE
not enabled by default after adding <router-outlet>

### ISSUE THREAD

**Issue by ashrafemad** [thevladeffect/ngx-typed-js#30]
I just used this library as described in the README
1- added the import to the Module I'm using it in [homepage]
2- added 
```
<ngx-typed-js [strings]="['a', 'b']">
      <h1 class="typing"></h1>
</ngx-typed-js>
```
to the homepage.component.html [in homepage module]

3- added `<router-outlet></router-outlet>` to the `app.component.html`

then after visiting the homepage route, the typed js element does not appear
but once I click on any button in the navbar (outside the homepage component) the element appears and works

anyone faced this?

Angular version: 12

**Comment by thevladeffect** [comment]
I can't replicate this with the latest release v2.1.1. Please try and if you still can make fork where this is replicated so I can investigate.
