### ISSUE TITLE
Fix for parameters visibility does not have release npm version

### ISSUE THREAD

**Issue by bopm** [thevladeffect/ngx-typed-js#32]
https://github.com/thevladeffect/ngx-typed-js/commit/062ee2c5ac4a6fcb162e5a08e71767a46c715e24 is not released on npm which makes this library unusable on Strict Angular. 

@thevladeffect can you please make a 2.1.1 release?

**Comment by thevladeffect** [comment]
This should be fixed in 2.1.1
